spring:
  
  ## Oracle Config ##
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USER}
#    password: ${DATABASE_PASSWORD}
    
  ## H2 ##
  h2:
    console:
      enabled: true
#  datasource:
#    url:  jdbc:h2:mem:testdb
#    username: sa
#    password: 
#    driver-class-name: org.h2.Driver
    
  ## JPA ##
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
 
  ## Thymeleaf ## 
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html\
    mode: HTML5
    check-template-location: true    cache: false  
  

logging:  level:    org.hibernate.SQL: debug
    # 파라미터 로그를 찍어주어요
    org.hibernate.type: trace 